DiscordStatus = "!pb help"
Instruct = "Instruct"
InstructCommandHelp = "help"
InstructCommandRaidDelayResponse = "RaidDelay for {{.ID}}:{{.Name}} is now {{.RaidDelay}}"
InstructCommandServer = "server"
InstructCommandServerAdd = "add"
InstructCommandServerAddUsage = "Usage: `server add <name>`"
InstructCommandServerChatHere = "chathere"
InstructCommandServerChatHereResponse = "Server {{.Name}} ({{.ID}}) will chat here"
InstructCommandServerDelete = "delete"
InstructCommandServerDeleteResponse = "Server {{.Name}} ({{.ID}}) removed"
InstructCommandServerDoesNotExist = "Invalid server ID. Check server list."
InstructCommandServerList = "list"
InstructCommandServerListHeader = "`ID\\tName\\tRaid Delay\\tKey`\\t"
InstructCommandServerRaidDelay = "raiddelay"
InstructCommandServerRaidDelayInvalidFormat = "Invalid duration format. Examples: `5m` = 5 minutes, `1h` = 1 hour, `1s` = 1 second"
InstructCommandServerRaidDelayUsage = "Usage: `server [id] raiddelay <duration>`"
InstructCommandServerRaidNotificationFrequencyInvalidFormat = "Invalid duration format. Examples: `5m` = 5 minutes, `1h` = 1 hour, `1s` = 1 second"
InstructCommandServerRaidNotificationFrequencyResponse = "RaidNotifyFrequency for {{.ID}}:{{.Name}} is now {{.RaidNotifyFrequency}}"
InstructCommandServerRaidNotificationFrequencyUsage = "Usage: `server [id] raidnotificationfrequency <duration>`"
InstructCommandServerRaidNotifyFrequency = "raidnotifyfrequency"
InstructCommandServerRename = "rename"
InstructCommandServerRenameUsage = "Usage: `server [id] rename <name>`"
InstructCommandServerReset = "reset"
InstructCommandStatus = "status"
InstructCommandUnregister = "unregister"
InstructInvalidCommand = "Invalid command. See `help`"
InstructNotAuthorized = "You are not authorized to use this commamd. This is only available to the server owner."
InstructResponseInvalidServerID = "Invalid server ID. See `help`."
InstructResponseMultipleServersDefines = "You have multiple servers defined. You must supply a server ID. See `server list` or `help`."
InternalError = "Internal error. Please try again."
InvalidCommand = "Invalid Command: {{.Command}}"
PINAuthenticated = "You have authenticated!"
PINInternalError = "Internal error. Please try again."
PINInvalid = "Invalid PIN. Please try again."
PINNotRequested = "ERROR: PIN is not required at this time. Check `status` or `help`."
TruncatedMessage = "*Truncated message to {{.Message}}"
UserPINPrompt = "Enter the PIN provided in-game to validate your account.\\nOnce you are validated, you will begin receiving raid alerts!"
