DiscordStatus = "!pb help"
Instruct = "Instruct"
InstructCommandServerAdd = "add"
InstructCommandServerAddUsage = "Usage: `server add <name>`"
InstructCommandServerChatHere = "chathere"
InstructCommandServerDelete = "delete"
InstructCommandServerDeleteResponse = "Server {{.Name}} ({{.ID}}) removed"
InstructCommandServerList = "list"
InstructCommandServerListHeader = "`ID\\tName\\tRaid Delay\\tKey`\\t"
InstructCommandServerRaidDelay = "raiddelay"
InstructCommandServerRaidDelayInvalidFormat = "Invalid duration format. Examples: `5m` = 5 minutes, `1h` = 1 hour, `1s` = 1 second"
InstructCommandServerRaidDelayUsage = "Usage: `server [id] raiddelay <duration>`"
InstructCommandServerRename = "rename"
InstructCommandServerRenameUsage = "Usage: `server [id] rename <name>`"
InstructCommandServerReset = "reset"
InstructResponseInvalidServerID = "Invalid server ID. See `help`."
InstructResponseMultipleServersDefines = "You have multiple servers defined. You must supply a server ID. See `server list` or `help`."
InstructServer = "server"
InstructionNotFromAdmin = "Instruction is not from an admin"
InvalidCommand = "Invalid Command: {{.Command}}"
PinAuthenticated = "You have authenticated!"
PinInternalError = "Internal error. Please try again."
PinInvalid = "Invalid pin. Please try again."
TruncatedMessage = "*Truncated message to {{.Message}}"
UserPINPrompt = "Enter the PIN provided in-game to validate your account.\\nOnce you are validated, you will begin receiving raid alerts!"
