[InstructCommandRaidDelayResponse]
hash = "sha1-2a6fa3afc92880c9a23e54b24dbcfc66018d576a"
other = "RaidDelay for {{.ID}}:{{.Name}} is now {{.RaidDelay}}"

[InstructCommandServerDoesNotExist]
hash = "sha1-50ab63d96be1af7a6fc9e477414575c2b971e6f8"
other = "Invalid server ID. Check server list."

[InstructCommandServerRaidNotificationFrequencyInvalidFormat]
hash = "sha1-b608ffb6418cf49658d19c626e9c2cb34b8f8f0a"
other = "Invalid duration format. Examples: `5m` = 5 minutes, `1h` = 1 hour, `1s` = 1 second"

[InstructCommandServerRaidNotificationFrequencyResponse]
hash = "sha1-8bd70a98a85c9282047ade77ec16a030f06b202f"
other = "RaidNotifyFrequency for {{.ID}}:{{.Name}} is now {{.RaidNotifyFrequency}}"

[InstructCommandServerRaidNotificationFrequencyUsage]
hash = "sha1-29bb72e62e1d546c956c803b26754ffc5333b9e8"
other = "Usage: `server [id] raidnotificationfrequency <duration>`"

[InstructCommandServerRaidNotifyFrequency]
hash = "sha1-779fb6e612f0ff9a5fd981b32384ffb76d493a65"
other = "raidnotifyfrequency"

[InstructCommandStatus]
hash = "sha1-48a3661d846478fa991a825ebd10b78671444b5b"
other = "status"

[InstructCommandUnregister]
hash = "sha1-6e736da0538cc13b3027e1b2df7d4e15fe99d3c2"
other = "unregister"

[InstructInvalidCommand]
hash = "sha1-099f3e365187b964e2892332a2cc7996ba267374"
other = "Invalid command. See `help`"

[InstructNotAuthorized]
hash = "sha1-a0fff1fc1961cef6a8e96b28259e3a098f1cdde2"
other = "You are not authorized to use this commamd. This is only available to the server owner."

[PINNotRequested]
hash = "sha1-49bb9d8173a548ff877ab5179e7772562911a874"
other = "ERROR: PIN is not required at this time. Check `status` or `help`."
