[DiscordStatus]
hash = "sha1-2ed558e8e7ffa8fdb8ee9bea432c1ade294ed2e8"
other = "!pb help"

[Instruct]
hash = "sha1-652511a3de956791adc75131e41f8d3f4b21689c"
other = "Instruct"

[InstructCommandServerAdd]
hash = "sha1-58d1bbce297de3c304a9fefc3b483181872a5c6b"
other = "add"

[InstructCommandServerAddUsage]
hash = "sha1-347cf263d0e0ede22bcda1fd98951bb12dd0218e"
other = "Usage: `server add <name>`"

[InstructCommandServerChatHere]
hash = "sha1-561e32aae36c4fd90e2b835bd2b3b1e47c5ac704"
other = "chathere"

[InstructCommandServerDelete]
hash = "sha1-9485989ff514b5106b7738850fd73c23e8c1e3f7"
other = "delete"

[InstructCommandServerDeleteResponse]
hash = "sha1-0206cff7362726c4efacf362259349bfb2156517"
other = "Server {{.Name}} ({{.ID}}) removed"

[InstructCommandServerList]
hash = "sha1-38b62be4bddaa5661c7d6b8e36e28159314df5c7"
other = "list"

[InstructCommandServerListHeader]
hash = "sha1-fdcbc499ac31f9b3f5b68042c6e58cc27f8e04db"
other = "`ID\\tName\\tRaid Delay\\tKey`\\t"

[InstructCommandServerRaidDelay]
hash = "sha1-ac72f77aa542309977a6af961629eae0986fb71d"
other = "raiddelay"

[InstructCommandServerRaidDelayInvalidFormat]
hash = "sha1-b608ffb6418cf49658d19c626e9c2cb34b8f8f0a"
other = "Invalid duration format. Examples: `5m` = 5 minutes, `1h` = 1 hour, `1s` = 1 second"

[InstructCommandServerRaidDelayUsage]
hash = "sha1-062ef6ecf2d3f3629de446ed0e16e9562ae88818"
other = "Usage: `server [id] raiddelay <duration>`"

[InstructCommandServerRename]
hash = "sha1-04a26d6f4aab9bc632ef3b0b244135354c76f93c"
other = "rename"

[InstructCommandServerRenameUsage]
hash = "sha1-4ce329fb690ed969ff2f2decc06b50a44bfd2bbe"
other = "Usage: `server [id] rename <name>`"

[InstructCommandServerReset]
hash = "sha1-91ef0c1608b20c9c5bd9e003bbb600229c0dfeb1"
other = "reset"

[InstructResponseInvalidServerID]
hash = "sha1-bfa2096206af6af67c270ccc6305e34df38b120b"
other = "Invalid server ID. See `help`."

[InstructResponseMultipleServersDefines]
hash = "sha1-82efc86f1b24d255d8929c5246ed7f600cd44c22"
other = "You have multiple servers defined. You must supply a server ID. See `server list` or `help`."

[InstructServer]
hash = "sha1-3de4f901fffb30ac720b0e7eb654b4faa2dd03fa"
other = "server"

[InstructionNotFromAdmin]
hash = "sha1-89470f3ba85ed6a82a1856598298d5252c045e31"
other = "Instruction is not from an admin"

[InvalidCommand]
hash = "sha1-87f4d877a6a140853aaaf433244b77e91e92ad78"
other = "Invalid Command: {{.Command}}"

[PinAuthenticated]
hash = "sha1-87bdf039b7c039d93497d62b805f71956691f666"
other = "You have authenticated!"

[PinInternalError]
hash = "sha1-51c49c603676bddc9f4eb42b58d215092cd9c72c"
other = "Internal error. Please try again."

[PinInvalid]
hash = "sha1-1ba597fb10f5130fc7df63a746ff4d985e4d4d1a"
other = "Invalid pin. Please try again."

[TruncatedMessage]
hash = "sha1-a73ede39702ee87ac6dd1427fbab7121cb664060"
other = "*Truncated message to {{.Message}}"

[UserPINPrompt]
hash = "sha1-4f3204d6afe0f3faba51e71be9d44fe929fde6af"
other = "Enter the PIN provided in-game to validate your account.\\nOnce you are validated, you will begin receiving raid alerts!"
