version: "3.7"
services:
  poundbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .poundbot.env
    depends_on:
      - mongo
  pb-proxy:
    image: pb-proxy
    build: _docker/nginx/
    ports:
      - 127.0.0.1:8080:8080
  mongo:
    image: mongo:4.2
    restart: unless-stopped
    volumes:
      - poundbot-data:/data/db
volumes:
  poundbot-data: