// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import time "time"
import "github.com/poundbot/poundbot/pkg/models"

// ChatQueueStore is an autogenerated mock type for the ChatQueueStore type
type ChatQueueStore struct {
	mock.Mock
}

// GetGameServerMessage provides a mock function with given fields: serverKey, tag, timeout
func (_m *ChatQueueStore) GetGameServerMessage(serverKey string, tag string, timeout time.Duration) (models.ChatMessage, bool) {
	ret := _m.Called(serverKey, tag, timeout)

	var r0 models.ChatMessage
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) models.ChatMessage); ok {
		r0 = rf(serverKey, tag, timeout)
	} else {
		r0 = ret.Get(0).(models.ChatMessage)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string, string, time.Duration) bool); ok {
		r1 = rf(serverKey, tag, timeout)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// InsertMessage provides a mock function with given fields: message
func (_m *ChatQueueStore) InsertMessage(message models.ChatMessage) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.ChatMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
